# news fetcher api app.yaml file contents:
runtime: python310
env: standard

service: getmachinanovanews

instance_class: F4_1G
automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: gunicorn -b :$PORT -t 18000 main:app