# news fetcher api app.yaml file contents:
runtime: python310
env: standard

service: getmachinanovanews

instance_class: F4_1G
automatic_scaling:
  min_instances: 0
  max_instances: 3

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  # Set the environment variables for your application here
  OPENAI_API_KEY: 'projects/869438047749/secrets/news-retriever-openai-key/versions/latest'

entrypoint: gunicorn -b :$PORT -t 18000 main:app